# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 6) do

  create_table "books", :force => true do |t|
    t.column "title",       :string
    t.column "url",         :text
    t.column "image",       :text
    t.column "author",      :string
    t.column "started_on",  :date
    t.column "created_at",  :datetime
    t.column "status",      :integer,  :default => 0
    t.column "finished_on", :date
    t.column "blurb",       :text
  end

  create_table "feed_items", :force => true do |t|
    t.column "title",      :string
    t.column "body",       :text
    t.column "link",       :text
    t.column "author",     :string
    t.column "created_at", :datetime
  end

  create_table "users", :force => true do |t|
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
  end

end
